name: Android CI

on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches-ignore:
      - 'dev'

jobs:
  build-all:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Go 1.18
      uses: actions/setup-go@v1
      with:
        go-version: 1.18
      id: go
    - name: Force NDK version
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;22.1.7171670"
    - name: Build rclone
      run: ./gradlew rclone:buildNative
    - name: Build app
      run: ./gradlew assembleOssDebug
    - name: Upload APK (arm)
      uses: actions/upload-artifact@v2
      with:
        name: arm.apk
        path: app/build/outputs/apk/oss/debug/app-oss-armeabi-v7a-debug.apk
        retention-days: 3
    - name: Upload APK (arm64)
      uses: actions/upload-artifact@v2
      with:
        name: arm64.apk
        path: app/build/outputs/apk/oss/debug/app-oss-arm64-v8a-debug.apk
        retention-days: 3
    - name: Upload APK (x86)
      uses: actions/upload-artifact@v2
      with:
        name: x86.apk
        path: app/build/outputs/apk/oss/debug/app-oss-x86-debug.apk
        retention-days: 3
    - name: Upload APK (arm)
      uses: actions/upload-artifact@v2
      with:
        name: x64.apk
        path: app/build/outputs/apk/oss/debug/app-oss-x86_64-debug.apk
        retention-days: 3
    - name: Upload APK (universal)
      uses: actions/upload-artifact@v2
      with:
        name: universal.apk
        path: app/build/outputs/apk/oss/debug/app-oss-universal-debug.apk
        retention-days: 14