name: Android CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    branches-ignore:
      - 'master'


jobs:
  createArtifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Set up Go 1.19.8
      uses: actions/setup-go@v4
      with:
        go-version: 1.19.8
      id: go
    - name: Install NDK
      run: |
        NDK_VERSION="$(grep -E "^de\.felixnuesse\.extract\.ndkVersion=" gradle.properties | cut -d'=' -f2)"
        yes | sudo "${ANDROID_HOME}/tools/bin/sdkmanager" --licenses
        sudo "${ANDROID_HOME}/tools/bin/sdkmanager" "ndk;${NDK_VERSION}"
    - name: Build app
      run: ./gradlew assembleOssDebug
    - name: Upload APK (arm)
      uses: actions/upload-artifact@v3
      with:
        name: nightly-armeabi.apk
        path: app/build/outputs/apk/oss/debug/roundsync_v*-oss-armeabi-v7a-debug.apk
        retention-days: 3
    - name: Upload APK (arm64)
      uses: actions/upload-artifact@v3
      with:
        name: nightly-arm64.apk
        path: app/build/outputs/apk/oss/debug/roundsync_v*-oss-arm64-v8a-debug.apk
        retention-days: 3
    - name: Upload APK (x86)
      uses: actions/upload-artifact@v3
      with:
        name: nightly-x86.apk
        path: app/build/outputs/apk/oss/debug/roundsync_v*-oss-x86-debug.apk
        retention-days: 3
    - name: Upload APK (arm)
      uses: actions/upload-artifact@v3
      with:
        name: nightly-x64.apk
        path: app/build/outputs/apk/oss/debug/roundsync_v*-oss-x86_64-debug.apk
        retention-days: 3
    - name: Upload APK (universal)
      uses: actions/upload-artifact@v3
      with:
        name: nightly-universal.apk
        path: app/build/outputs/apk/oss/debug/roundsync_v*-oss-universal-debug.apk
        retention-days: 14